name: Build Flutter PWA

on:
  push:
    branches: 
      - stagging

jobs:
  build:
    name: Build Web
    
    env:
      my_secret: ${{secrets.commit_secret}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release
    - run: |
        cd build/web
        git init
        git config --global user.email rkanon123@gmail.com
        git config --global user.name Rona Kilmer
        git status
        git remote add origin https://${{secrets.commit_secret}}@github.com/rkunboxed/rkunboxed.github.io.git
        git checkout -b master
        git add --all
        git commit -m "update website"
        git push origin master -f
